Traceback (most recent call last):
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pewhite/.asdf/installs/python/3.11.9/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/pewhite/github/aet-cs/aet-cs.github.io/white/ML/env/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
scores = []
for i in range(50):
    df = get_data(filename)
    df = pre_process_data(df, one_hot_encode = True)
    X_train, X_test, y_train, y_test = get_test_train(df)
    lreg = LinearRegression()
    model = lreg.fit(X_train, y_train)
    scores += [model.score(X_test, y_test)]
plt.scatter(x = range(len(scores)), y = scores);
plt.title("$r^2$ of 50 Linear regression Models with Normalization")
print(f"Linear Model: Mean score = {np.mean(scores):.3} Stdev = {np.std(scores):.3}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 5[0m
[1;32m      3[0m df [38;5;241m=[39m get_data(filename)
[1;32m      4[0m df [38;5;241m=[39m pre_process_data(df, one_hot_encode [38;5;241m=[39m [38;5;28;01mTrue[39;00m)
[0;32m----> 5[0m X_train, X_test, y_train, y_test [38;5;241m=[39m [43mget_test_train[49m[43m([49m[43mdf[49m[43m)[49m
[1;32m      6[0m lreg [38;5;241m=[39m LinearRegression()
[1;32m      7[0m model [38;5;241m=[39m lreg[38;5;241m.[39mfit(X_train, y_train)

Cell [0;32mIn[12], line 6[0m, in [0;36mget_test_train[0;34m(df, test_size, random_state)[0m
[1;32m      3[0m X [38;5;241m=[39m df[38;5;241m.[39mdrop(target, axis[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      5[0m [38;5;66;03m# add a scaler here. It works by finding a fit first (computing mu and sigma)[39;00m
[0;32m----> 6[0m scaler [38;5;241m=[39m [43mpreprocessing[49m[38;5;241m.[39mStandardScaler()[38;5;241m.[39mfit(X)
[1;32m      7[0m [38;5;66;03m# and then transforming the data[39;00m
[1;32m      8[0m X [38;5;241m=[39m scaler[38;5;241m.[39mtransform(X)

[0;31mNameError[0m: name 'preprocessing' is not defined

